add storage file
rmjspecial/To-Do-List-App pull request #3
Opened 2022-07-08 18:58 UTC by rmjspecial

**Project-Description**

- Add footer method to clear all computed tasks.
- Add an update storage message to clear all computed storage.

2022-07-08 20:12 UTC, medaminedev66 requested changes
Hi @rmjspecial  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- There are no linter errors
- All the completed tasks are removed after clicking on the clear all completed tasks button.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 20:12 UTC, medaminedev66 commented on src/clear.js
>  };
- [ ] The user should get the correct list values after the page reloads. Please make sure when you reload the page the checkboxes next to the tasks are checked if the tasks are completed.

2022-07-08 20:12 UTC, medaminedev66 commented on src/clear.js
> +  setStorage(data);
- [ ] When I reload the page and try to change the checkbox of a task, the completed value of all the other tasks changes to false in the local storage. Please correct that.

2022-07-09 13:09 UTC, rmjspecial commented
fix all issues according to the requirements.

2022-07-09 13:18 UTC, FrederickMih approved these changes
# Status: Approved :tada: :tada: 

Hi @rmjspecial , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 13:24 UTC, merged